### ISSUE TITLE
Seems to remove fish from Carnivore?

### ISSUE THREAD

**Issue by Traehgniw** [LuaDotExe/We-Have-the-Meats#1] opened 2023-01-23 01:11 UTC
I put this datapack in my 1.18.2 Origins setup and fish are listed as Inedible due to Carnivore. But fish meat is still meat?

Also unrelatedly I feel like carnivores should also be able to eat eggs, and dishes with a little bit of vegetable in them. Real-life carnivores do eat the stomach contents of their prey, and it just feels weird to have Pepperoni be Inedible due to Carnivore when it's just...meat with seasoning.

**Comment by LuaDotExe** [comment] 2023-01-24 00:25
Fish being inedible is unintended; it works just fine in 1.19.2. While investigating this issue, I've come to the conclusion that it's linked to the logic behind the Carnivore/Vegetarian Powers that I'm editing. I've decided that the best and easiest solution is to simply remove the #origins_meat_compat:vegetarian tag and its functionality. This will be fixed in 1.2.1, and is also likely the cause for the pepperoni-related issue (although I'm not sure what modded pepperoni you're referring to).

**Comment by Traehgniw** [comment] 2023-01-24 22:15
It was Croptopia pepperoni!

Thank you for this. Will the 1.2.1 version be loadable in 1.18.2?

**Comment by LuaDotExe** [comment] 2023-01-24 23:16
Yes, it can be loaded into 1.18.2. I'll start investigating the pepperoni now.

**Comment by Traehgniw** [comment] 2023-01-24 23:34
Pepperoni's recipe in Croptopia is a meat, plus a pepper, plus some paprika! Other Croptopia recipes that it made inedible that would make sense to be edible for carnivores were lemon chicken, bacon (cooked and raw), ground pork, sausage, everything to do with calarami, beef wellington, oysters both raw and grilled, clams both raw and steamed, and fried chicken. 
(Aka, it made everything from Croptopia inedible to carnivores.)

It also inexplicably made both Additional Additions and Burgermod chicken nuggets inedible to carnivores.

**Comment by Traehgniw** [comment] 2023-01-24 23:41
Further testing: Croptopia-added seafood is inedible to carnivores even without the datapack, so adding the fish and invertebrate seafood to origins:meat would be a neat thing for this datapack to do!

**Comment by Traehgniw** [comment] 2023-01-26 00:19
1.2.1 fixes the removed-fish issue and the inedible croptopia bacon but does not fix the pepperoni & ground pork issues. Still, my carnivore guy can now eat fish and bacon again! yay!


ETA: Raw Croptopia seafood is now edible with this datapack (it is not edible to Carnivore without) but the cooked ones still aren't.

**Closed as completed** 2023-02-02 06:55 UTC
